# Generated by Django 2.2.14 on 2020-07-11 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0002_auto_20200711_1951'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
